dependencies:
  - name: nginx-ingress
    version: 1.17.1
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: cert-manager
    version: v0.9.0
    repository: https://charts.jetstack.io
  - name: keycloak
    version: 5.1.6
    repository: https://codecentric.github.io/helm-charts
  - name: postgresql
    version: 5.3.9
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: keycloak.persistence.deployPostgres