apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: keycloak-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    {{ if .Values.cert.production }}
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    {{- else }}
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
    {{- end }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
  - hosts:
    - web-wlf-cert.westeurope.cloudapp.azure.com
    secretName: tls-secret
  rules:
  - host: web-wlf-cert.westeurope.cloudapp.azure.com
    http:
      paths:
      - backend:
          serviceName: {{ include "keycloak.fullname" . }}-http
          servicePort: 8080
        path: /auth/(.*)